# Generated by Django 4.2 on 2023-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_clues_clueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userEmail', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('userPass', models.CharField(max_length=255)),
                ('scoreAndTime', models.JSONField(null=True)),
                ('totalScore', models.CharField(max_length=100, null=True)),
                ('totalTime', models.CharField(max_length=100, null=True)),
                ('attempts', models.IntegerField(null=True)),
            ],
        ),
    ]
