# Generated by Django 4.2 on 2023-04-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_users_scoreandtime_alter_users_userpass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='scoreAndTime',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ScoreAndTime',
        ),
    ]
