# Generated by Django 4.2 on 2023-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_users_scoreandtime_scoreandtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreandtime',
            name='id',
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='userEmail',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
