# Generated by Django 4.2 on 2023-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_scoreandtime_id_alter_scoreandtime_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl0Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl1Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl2Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl3Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl4Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl5Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl6Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl7Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl8Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scoreandtime',
            name='cl9Tym',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='attempts',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
